### ISSUE TITLE
Explore options for improving sensor contact network stability

### ISSUE THREAD

**Issue by alexanderson1993** [Thorium-Sim/thorium#1263]
## Detailed Description

- Send regular network messages

- Utilize UDP when using the client application

- ⭐️ Interpolate the current state to the server state when new data comes in.

**Comment by brentjanderson** [comment]
Have you checked to see if TCP overhead is causing issues for sensors?

**Comment by alexanderson1993** [comment]
I don’t think I have. How would that make a difference?

**Comment by brentjanderson** [comment]
Why change to udp if it may not help? Is the latency network related or higher up the stack?

**Comment by alexanderson1993** [comment]
No idea. I was just listing options.

**Comment by Emrix** [comment]
@alexanderson1993, has this basically become fixed with your experiments on client side interpolation using CRM?

**Comment by alexanderson1993** [comment]
It’s not fixed, since I haven’t implemented anything , but it’s a non-issue at this point - nobody complains about the sensors anymore.
